services:
    bordeux.geoname.import.timezone:
        class: Bordeux\Bundle\GeoNameBundle\Import\TimeZoneImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    bordeux.geoname.import.administrative:
        class: Bordeux\Bundle\GeoNameBundle\Import\AdministrativeImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    bordeux.geoname.import.geoname:
        class: Bordeux\Bundle\GeoNameBundle\Import\GeoNameImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true


    bordeux.geoname.import.country:
        class: Bordeux\Bundle\GeoNameBundle\Import\CountryImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    bordeux.geoname.import.hierarchy:
        class: Bordeux\Bundle\GeoNameBundle\Import\HierarchyImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true


    #auto register all commands
    Bordeux\Bundle\GeoNameBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']