language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
services:
  - mysql

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  include:
    - php: 5.5
      env: deps=low SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*@dev"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*@dev"

env:
  global:
    - deps=no

before_install:
  - mysql -e 'CREATE DATABASE geo_test;'
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi;

install:
  - if [ "$deps" = "no" ]; then composer update; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;
  - ./Tests/Resources/app/console doctrine:schema:update --force
  - ./Tests/Resources/app/console bordeux:geoname:import --archive http://download.geonames.org/export/dump/PL.zip


script:
  - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
